name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Hostinger
        run: |
          # Comprime o conteúdo da pasta build
          tar -czf build.tar.gz -C build .
          # Envia o arquivo comprimido para o servidor via SCP
          scp -o StrictHostKeyChecking=no build.tar.gz ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}:~/public_html/
          # Conecta-se ao servidor via SSH, descomprime e organiza os arquivos
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }} << 'EOF'
            cd ~/public_html/
            tar -xzf build.tar.gz
            rm build.tar.gz
          EOF
    env:
      HOSTINGER_USER: ${{ secrets.HOSTINGER_USER }}
      HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}
