name: Deploy React App to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Fazer o checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Garantir que ferramentas necessárias estão instaladas
      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      # 3. Compactar e transferir os arquivos para o servidor
      - name: Deploy to Hostinger
        run: |
          tar -czf build.tar.gz -C build .
          scp -o StrictHostKeyChecking=no build.tar.gz ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}:~
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }} << EOF
            rm -rf ~/public_html/*
            tar -xzf ~/build.tar.gz -C ~/public_html/
            rm ~/build.tar.gz
          EOF

      # 4. Debug de secrets (apenas para confirmar o uso, sem expor valores confidenciais)
      - name: Debug Secrets
        run: |
          echo "HOSTINGER_USER set: [OK]"
          echo "HOSTINGER_HOST set: [OK]"
